// Converts HTML files in data/ to gzipped C byte arrays in include/html_*.h
// Follows the WLED / DartLaser pattern.
// Also generates include/version.h from package.json `version` and substitutes
// {{VERSION}} / {{BUILD_DATE}} placeholders in HTML before gzipping so the
// running firmware and the served pages report the same version string.
// Usage: node tools/cdata.js

const fs   = require('fs');
const path = require('path');
const zlib = require('zlib');
const { execSync } = require('child_process');

const rootDir = path.join(__dirname, '..');
const dataDir = path.join(rootDir, 'data');
const outDir  = path.join(rootDir, 'include');

// ── Version ────────────────────────────────────────────────────────────────
const pkg = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
const version = pkg.version || '0.0.0';
const [vMaj, vMin, vPatch] = version.split('.').map(n => parseInt(n, 10) || 0);

let gitHash = '';
try {
  gitHash = execSync('git rev-parse --short HEAD', { cwd: rootDir, stdio: ['ignore','pipe','ignore'] })
    .toString().trim();
} catch (_) { /* not a git repo or git missing — fine */ }

const buildTime = Math.floor(Date.now() / 1000);
const buildDate = new Date(buildTime * 1000).toISOString().slice(0, 10);
const versionStr = gitHash ? `${version}+${gitHash}` : version;

// Write include/version.h — single source for both firmware and Art-Net reply.
const verH =
`// Auto-generated by tools/cdata.js — do not edit!
// Source: package.json (version: ${version})
#pragma once

#define FW_VERSION_STRING   "${versionStr}"
#define FW_VERSION_MAJOR    ${vMaj}
#define FW_VERSION_MINOR    ${vMin}
#define FW_VERSION_PATCH    ${vPatch}
#define FW_BUILD_TIME       ${buildTime}
#define FW_BUILD_DATE       "${buildDate}"
#define FW_GIT_HASH         "${gitHash}"
`;
fs.writeFileSync(path.join(outDir, 'version.h'), verH);
console.log(`  version.h: v${versionStr} (build ${buildDate})`);

// ── HTML → gzip → header ───────────────────────────────────────────────────
const files = fs.readdirSync(dataDir).filter(f => f.endsWith('.html'));

if (files.length === 0) {
  console.log('  No HTML files found in data/ — skipping.');
  process.exit(0);
}

files.forEach(file => {
  const name    = path.basename(file, '.html');
  const varName = 'PAGE_' + name;
  let   srcStr  = fs.readFileSync(path.join(dataDir, file), 'utf8');

  // Substitute version placeholders. Pages may use {{VERSION}} or {{BUILD_DATE}}.
  srcStr = srcStr
    .replace(/\{\{VERSION\}\}/g,    versionStr)
    .replace(/\{\{BUILD_DATE\}\}/g, buildDate);

  const src = Buffer.from(srcStr, 'utf8');
  const gz  = zlib.gzipSync(src, { level: zlib.constants.Z_BEST_COMPRESSION });

  let out = '';
  out += `// Auto-generated by tools/cdata.js — do not edit!\n`;
  out += `// Source: data/${file}  (${src.length} bytes -> ${gz.length} bytes gzip)\n`;
  out += `#pragma once\n\n`;
  out += `#include <Arduino.h>\n\n`;
  out += `#define WEB_BUILD_TIME ${buildTime}\n\n`;
  out += `const uint16_t ${varName}_length = ${gz.length};\n`;
  out += `const uint8_t ${varName}[] PROGMEM = {\n`;

  const lines = [];
  for (let i = 0; i < gz.length; i += 16) {
    const chunk = gz.slice(i, Math.min(i + 16, gz.length));
    lines.push('  ' + Array.from(chunk).map(b => '0x' + b.toString(16).padStart(2, '0')).join(', '));
  }
  out += lines.join(',\n');
  out += `\n};\n`;

  const outPath = path.join(outDir, `html_${name}.h`);
  fs.writeFileSync(outPath, out);
  console.log(`  ${file}: ${src.length} -> ${gz.length} bytes (${(gz.length / src.length * 100).toFixed(1)}%) -> html_${name}.h`);
});
